import type { NextPage } from 'next'
import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import GoogleIcon from '@mui/icons-material/Google';
import LogoutIcon from '@mui/icons-material/Logout';
import Tooltip from '@mui/material/Tooltip';

const Header: NextPage = () => {
  const { data: session } = useSession()

  if (!session) {
    return (
      <>
      <Head>
        <title>React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <Grid
          container
          columns={{ xs: 4, sm: 8, md: 12 }}
          direction="row"
          justifyContent="space-between"
          alignItems="baseline"
          p={2}
        >
          <Grid>

          </Grid>
          <Grid>
            <Tooltip title="Sign in | Google">
            <IconButton onClick={() => signIn('google', { callbackUrl: '/notas' }) } aria-label="delete" size="large">
              <GoogleIcon fontSize="large" />
            </IconButton>
            </Tooltip>
          </Grid>
          <Grid>

          </Grid>
        </Grid>
      </Box>
      </>
    )
  }

  return (
    <>
      <Head>
        <title>React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
      </Head>

      <Box sx={{ flexGrow: 1 }}>
        <Grid
          container
          columns={{ xs: 4, sm: 8, md: 12 }}
          direction="row"
          justifyContent="space-between"
          alignItems="baseline"
          p={2}
        >
          <Grid>
            <Typography variant="overline" display="block" gutterBottom>
              Signed in as {session?.user ? session.user.name : ''} 
            </Typography>
          </Grid>
          <Grid>

          </Grid>
          <Grid>
            <Tooltip title="Sign out">
            <IconButton onClick={() => signOut({ callbackUrl: '/' })} aria-label="delete" size="large">
              <LogoutIcon fontSize="inherit" />
            </IconButton>
            </Tooltip>
          </Grid>
        </Grid>
      </Box>
    </>
  )
}

export default Header
